/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_lk3;
import javax.swing.*;
/**
 *
 * @author zaenalalfian
 */
public class Form2a extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form2a
     */
    public Form2a() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ambilAwal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ambilAkhir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cetak = new javax.swing.JList<>();
        tombolFor = new javax.swing.JButton();
        tombolWhile = new javax.swing.JButton();
        tombolDowhile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PROGRAM LOOPING");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("PERULANGAN FOR, WHILE, DO WHILE");

        jLabel2.setText("Angka Awal");

        jLabel3.setText("Angka Akhir");

        jScrollPane1.setViewportView(cetak);

        tombolFor.setText("FOR");
        tombolFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolForActionPerformed(evt);
            }
        });

        tombolWhile.setText("WHILE");
        tombolWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolWhileActionPerformed(evt);
            }
        });

        tombolDowhile.setText("DO WHILE");
        tombolDowhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolDowhileActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/zaenal.png"))); // NOI18N
        jLabel4.setText("ZAENAL ALFIAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ambilAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ambilAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tombolFor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tombolWhile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tombolDowhile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ambilAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ambilAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombolFor)
                        .addGap(18, 18, 18)
                        .addComponent(tombolWhile)
                        .addGap(18, 18, 18)
                        .addComponent(tombolDowhile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolForActionPerformed
       DefaultListModel mdl= new DefaultListModel();
        int i,bil;
        
       bil=Integer.parseInt(ambilAkhir.getText());
       i=Integer.parseInt(ambilAwal.getText());
       for(i=i;i<=bil;i++){
           mdl.addElement(i);
           cetak.setModel(mdl);
       }
    }//GEN-LAST:event_tombolForActionPerformed

    private void tombolWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolWhileActionPerformed
        DefaultListModel mdl=new DefaultListModel();
        int i,bil;
        
       bil=Integer.parseInt(ambilAkhir.getText());
       i=Integer.parseInt(ambilAwal.getText());
       while (i<=bil){
           mdl.addElement(i);
           cetak.setModel(mdl);
           i=i+1;
       }
        
    }//GEN-LAST:event_tombolWhileActionPerformed

    private void tombolDowhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolDowhileActionPerformed
         DefaultListModel mdl=new DefaultListModel();
        int i,bil;
        
       bil=Integer.parseInt(ambilAkhir.getText());
       i=Integer.parseInt(ambilAwal.getText());
       for(i=i;i<=bil;i++){
           mdl.addElement(i);
           cetak.setModel(mdl); 
       }
    }//GEN-LAST:event_tombolDowhileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ambilAkhir;
    private javax.swing.JTextField ambilAwal;
    private javax.swing.JList<String> cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tombolDowhile;
    private javax.swing.JButton tombolFor;
    private javax.swing.JButton tombolWhile;
    // End of variables declaration//GEN-END:variables
}
