/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_lk3;

import java.awt.*;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Polygon;
import java.awt.geom.Rectangle2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.GeneralPath;
/**
 *
 * @author zaenalalfian
 */
public class Form1c extends javax.swing.JInternalFrame {
    public static final int Canvas_Width=500;
    public static final int Canvas_Height=450;
    private String jenis;
    /**
     * Creates new form Form1c
     */
    public Form1c() {
        initComponents();
        jenis="Kotak";
        setPreferredSize(new Dimension(Canvas_Width,Canvas_Height));
    }
//membuat bangun datar kotak,lingkaran,segitiga,garis
    public void kotak(Graphics g){
        
        setBackground(Color.WHITE);
        //setContentPane(new Form3a());
        Graphics2D g2=(Graphics2D) g;
        g2.setPaint(Color.MAGENTA);
        g2.draw(new Rectangle2D.Double(20,50, 80, 20));
        g2.fill(new Rectangle2D.Double(20,150, 100, 50));                  
        
    }
    public void lingkaran(Graphics g){
        setBackground(Color.YELLOW);
        Graphics2D g2=(Graphics2D) g;
        g2.setPaint(Color.blue);
        g2.draw(new Ellipse2D.Double(20,50, 100, 50));
        g2.fill(new Ellipse2D.Double(20,120, 100, 50));
    }
        
    public void segitiga(Graphics g){
        setBackground(Color.WHITE);
        Graphics2D g2=(Graphics2D) g;
       g2.setPaint(Color.RED);
       double x[]={183,72,45};
       double y[]={196,72,196};
     
       
       GeneralPath p=new GeneralPath();
       p.moveTo(x[0], y[0]);
       for (int i=1;i<x.length;i++){
           p.lineTo(x[i],y[i]);
            }
   	   g2.fill(p);
       }
        
    public void garis(Graphics g){
        setBackground(Color.WHITE);
        Graphics2D g2=(Graphics2D) g;
       g2.setPaint(Color.RED);
       double x[]={100,200,200,300,300,400,400,500,500,600};
       double y[]={300,300,150,150,300,300,50,50,300,300};
       
       GeneralPath p=new GeneralPath();
       p.moveTo(x[0], y[0]);
       for (int i=1;i<x.length;i++){
           p.lineTo(x[i],y[i]);
                      
       }
       g2.draw(p);      
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //switch case untuk menggambar jenis bangun datar
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        switch(jenis){
            case "Kotak":
                kotak(g);
                break;
                case "Lingkaran":
                lingkaran(g);
                break;
                 case "Segitiga":
                segitiga(g);
                break;
                
                case "Garis":
                garis(g);
                break;
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        pilihan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PROGRAM BANGUN DATAR");

        judul.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        judul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/applications-all.png"))); // NOI18N
        judul.setText("BIDANG DATAR");

        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kotak", "Lingkaran", "Segitiga", "Garis" }));
        pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanActionPerformed(evt);
            }
        });

        jLabel1.setText("Pilih Yang Mana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanActionPerformed
        String pil;
        pil=(String)pilihan.getSelectedItem();
        
        switch(pil){
            case "Kotak":
                jenis="Kotak";
                Form1c satu_c=new Form1c();
                setContentPane(satu_c);              
                repaint();
                satu_c.setDefaultCloseOperation(PROPERTIES);
                satu_c.pack();
                break;
                case "Lingkaran":
                jenis="Lingkaran";
                setContentPane(new Form1c());
                repaint();
                break;
                case "Segitiga":
                jenis="Segitiga";
                setContentPane(new Form1c());
                repaint();
                break;
                case "Garis":
                jenis="Garis";
                setContentPane(new Form1c());
                repaint();
                break;
        }
    }//GEN-LAST:event_pilihanActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel judul;
    private javax.swing.JComboBox<String> pilihan;
    // End of variables declaration//GEN-END:variables
}
